[client]
showSidebarNavigation = false

[theme]
# 主色调
primaryColor = "#1E88E5"  # 蓝色

# 背景色
backgroundColor = "#FFFFFF"  # 白色

# 次要背景色
secondaryBackgroundColor = "#F0F2F6"  # 浅灰色

# 文本颜色
textColor = "#262730"  # 深灰色

# 字体
font = "sans serif"